allow_tf32: false
aug: ada
augpipe: bgc
batch_size: 4
cfg: auto
cond: false
data: /workspace/dataset
dry_run: false
fp32: true
freezed: 0
gpus: 1
kimg: 100
metrics: []
mirror: true
nhwc: false
nobench: false
num_workers: 2
outdir: /workspace/training_output
resolution: 1024
resume: null
seed: 42
snap: 25
subset: null
target: 0.6
