# Minimal MonoX config for debugging hydra.strict error
# This config has absolutely no hydra.strict references

defaults:
  - _self_

# Basic structure
struct: false
exp_suffix: ""
num_gpus: 1

# Dataset
dataset:
  path: ""
  resolution: 1024
  c_dim: 0

# Training  
training:
  total_kimg: 3000
  snapshot_kimg: 250
  log_dir: logs

# Visualizer
visualizer:
  save_every_kimg: 50
  output_dir: previews

# Sampling
sampling:
  truncation_psi: 1.0

# Only essential hydra config
hydra:
  run:
    dir: logs