# Base dataset configuration
# Default dataset settings that can be overridden

_target_: ~
_recursive_: false

path: ${oc.env:DATASET_DIR,""}
resolution: 1024
c_dim: 0  # Conditional dimension (0 for unconditional generation)