# MonoX Training Configuration - 1024x1024 Resolution
# ====================================================
# Optimized for high-resolution StyleGAN-V training
# ====================================================

# Training parameters optimized for 1024x1024
total_kimg: 3000  # Total training images in thousands
snapshot_kimg: 250  # Save checkpoint every 250k images
image_snapshot_ticks: 50  # Save sample images every 50 ticks

# Batch configuration for 1024x1024 resolution
batch_size: 4  # Reduced for memory efficiency at 1024x1024
batch_gpu: 4   # Batch size per GPU
num_workers: 4  # Data loader workers

# Memory optimization
fp16: true  # Mixed precision training
gradient_accumulation: 1
memory_efficient: true

# Learning rate schedule
lr:
  generator: 0.002
  discriminator: 0.002
  mapping_network: 0.002
  beta1: 0.0
  beta2: 0.99
  epsilon: 1e-8

# StyleGAN-V specific settings for 1024x1024
stylegan_v:
  resolution: 1024
  z_dim: 512
  w_dim: 512
  mapping_layers: 8
  
  # Architecture settings for 1024x1024
  synthesis:
    channel_base: 32768  # Base channel multiplier
    channel_max: 512     # Maximum channels
    num_layers: auto     # Auto-calculate for 1024x1024
    
  discriminator:
    channel_base: 32768
    channel_max: 512
    block_resolutions: [1024, 512, 256, 128, 64, 32, 16, 8, 4]

# Regularization
regularization:
  r1_gamma: 10.0  # R1 regularization strength
  path_regularize: 2.0  # Path length regularization
  
# Progressive growing (if enabled)
progressive:
  enabled: false  # Disabled for direct 1024x1024 training
  start_resolution: 4
  grow_kimg: 600

# Output directories
output:
  log_dir: "logs"
  checkpoint_dir: "checkpoints" 
  sample_dir: "samples"
  
  # HF Model repository sync
  model_repo: "lukua/monox-model"
  sync_interval: 250  # Sync every 250k images
  
# Hardware optimization
hardware:
  num_gpus: 1
  mixed_precision: true
  compile_model: false  # Disable for compatibility
  
# Monitoring and logging
monitoring:
  log_interval: 100  # Log every 100 iterations
  sample_interval: 1000  # Generate samples every 1000 iterations
  checkpoint_interval: 250000  # Save checkpoint every 250k images
  
# Resume training
resume:
  auto_resume: true
  checkpoint_path: ""  # Auto-detect latest checkpoint