# RunPod Configuration for MonoX StyleGAN-V Training

# GPU Selection
gpu_types:
  t4: 
    memory: "16GB"
    cost_per_hour: 0.20
    recommended_batch_size: 4
  v100:
    memory: "32GB" 
    cost_per_hour: 0.50
    recommended_batch_size: 8
  a100:
    memory: "40GB"
    cost_per_hour: 1.50
    recommended_batch_size: 12
  rtx4090:
    memory: "24GB"
    cost_per_hour: 0.80
    recommended_batch_size: 6

# Training Configuration
training:
  epochs: 50
  checkpoint_interval: 10
  sample_interval: 5
  log_interval: 1
  mixed_precision: true
  gradient_accumulation: 2

# Storage Configuration
storage:
  persistent_volume: "/workspace"
  checkpoint_dir: "/workspace/checkpoints"
  sample_dir: "/workspace/samples"
  log_dir: "/workspace/logs"

# Model Configuration
model:
  noise_dim: 512
  output_resolution: 1024
  learning_rate: 2e-4
  beta1: 0.5
  beta2: 0.999

# RunPod Specific
runpod:
  auto_start: true
  auto_stop: true
  idle_timeout: 300  # 5 minutes
  max_runtime: 7200  # 2 hours
  spot_instance: true