# Clean Hydra configuration for MonoX StyleGAN-V training
# Updated for Hydra 1.3.x compatibility

defaults:
  - dataset: base
  - training: base  
  - visualizer: base
  - _self_

# Experiment configuration
exp_suffix: "monox"

# Hardware configuration
num_gpus: 1

# Dataset configuration
dataset:
  path: ${oc.env:DATASET_DIR,/content/MonoX/dataset}
  resolution: 1024
  c_dim: 0

# Training configuration
training:
  total_kimg: 3000
  snapshot_kimg: 250
  batch_size: 4
  num_workers: 4
  fp16: true
  num_gpus: 1
  log_dir: ${oc.env:LOGS_DIR,/content/MonoX/results/logs}
  preview_dir: ${oc.env:PREVIEWS_DIR,/content/MonoX/results/previews}
  checkpoint_dir: ${oc.env:CKPT_DIR,/content/MonoX/results/checkpoints}
  resume: ""

# Sampling configuration
sampling:
  truncation_psi: 1.0
  num_samples: 16

# Visualization configuration
visualizer:
  save_every_kimg: 50
  output_dir: ${oc.env:PREVIEWS_DIR,/content/MonoX/results/previews}
  grid_size: 4

# Hydra configuration
hydra:
  run:
    dir: ${oc.env:LOGS_DIR,/content/MonoX/results/logs}
  job:
    chdir: false