# Ultra minimal config - absolutely no hydra references
exp_suffix: ""
num_gpus: 1

dataset:
  path: ""
  resolution: 1024
  c_dim: 0

training:
  total_kimg: 3000
  snapshot_kimg: 250
  log_dir: logs

visualizer:
  save_every_kimg: 50
  output_dir: previews

sampling:
  truncation_psi: 1.0