# Minimal Hydra config for MonoX StyleGAN-V launcher
# You can override any of these via CLI: e.g.
#   python src/infra/launch.py dataset.path=/content/drive/MyDrive/MonoX/dataset training.log_dir=/content/drive/MyDrive/MonoX/logs

defaults:
  - dataset: base
  - training: base
  - visualizer: base
  - _self_

# Allow unknown fields to be added via + syntax
# Configuration settings for MonoX training

# Experiment configuration - Allows CLI override via exp_suffix=...
exp_suffix: null

# Hardware configuration
num_gpus: 1  # Number of GPUs to use for training

# No hydra configuration - let it use defaults

training:
  total_kimg: 1000  # Fresh training start
  snapshot_kimg: 50  # Save every 5 epochs (50 kimg ≈ 5 epochs)
  steps: null  # Override total_kimg if set (for quick testing)
  batch: 4  # Smaller batch for CPU/limited GPU
  num_workers: 2  # Reduced workers for stability
  fp16: false  # Disable for CPU training
  num_gpus: 0  # CPU training (will auto-detect GPU if available)
  log_dir: ${oc.env:LOGS_DIR,/workspace/logs}
  preview_dir: ${oc.env:PREVIEWS_DIR,/workspace/previews}
  checkpoint_dir: ${oc.env:CKPT_DIR,/workspace/checkpoints}
  resume: ""  # Fresh training from scratch

# Training mode/launcher
launcher: stylegan  # Options: stylegan, local

sampling:
  truncation_psi: 1.0

