# Minimal Hydra config for MonoX StyleGAN-V launcher
# You can override any of these via CLI: e.g.
#   python src/infra/launch.py dataset.path=/content/drive/MyDrive/MonoX/dataset training.log_dir=/content/drive/MyDrive/MonoX/logs

defaults:
  - _self_
  - dataset: base
  - training: base
  - visualizer: base

# Allow unknown fields to be added via + syntax
_target_: ~
_recursive_: false

# Experiment configuration
exp_suffix: ""  # Experiment name suffix

# hydra.run.dir override for output paths
hydra:
  run:
    dir: ${training.log_dir}
  job:
    override_dirname: null
  mode: RUN
  
# Disable struct mode to allow dynamic config additions
struct: false

training:
  total_kimg: 3000
  snapshot_kimg: 250
  steps: null  # Override total_kimg if set (for quick testing)
  batch: null  # Batch size override
  num_workers: null  # DataLoader workers override
  fp16: null  # Mixed precision override
  num_gpus: 1
  log_dir: ${oc.env:LOGS_DIR,logs}
  preview_dir: ${oc.env:PREVIEWS_DIR,previews}
  checkpoint_dir: ${oc.env:CKPT_DIR,checkpoints}
  resume: ""

# Training mode/launcher
launcher: stylegan  # Options: stylegan, local

sampling:
  truncation_psi: 1.0

