# MonoX StyleGAN-V Configuration - 1024x1024 Resolution (STRICT MODE)
# =======================================================================
# STRICT REQUIREMENT: Must use 'lukua/monox-dataset' (private dataset)
# No fallbacks allowed - training will fail if dataset is not accessible
# =======================================================================

defaults:
  - dataset: monox_dataset
  - training: monox_1024
  - visualizer: monox
  - _self_

# Experiment configuration
exp_suffix: "monox_1024_strict"

# Hardware configuration
num_gpus: 1  # Number of GPUs to use for training

# STRICT DATASET ENFORCEMENT
dataset:
  name: "lukua/monox-dataset"
  path: "lukua/monox-dataset"  # HF dataset identifier
  resolution: 1024
  c_dim: 0  # Unconditional generation
  private: true  # Requires authentication
  streaming: true  # Use streaming for large datasets
  validation_required: true  # STRICT: Must validate before training

# Training configuration optimized for 1024x1024
training:
  total_kimg: 3000
  snapshot_kimg: 250
  batch_size: 4  # Adjusted for 1024x1024 resolution
  num_workers: 4
  fp16: true  # Mixed precision for memory efficiency
  num_gpus: 1
  
  # Output directories (will be synced to lukua/monox-model)
  log_dir: "logs"
  preview_dir: "samples" 
  checkpoint_dir: "checkpoints"
  
  # Model repository sync
  model_repo: "lukua/monox-model"
  sync_outputs: true
  
  # Resume from checkpoint if available
  resume: ""
  auto_resume: true

# StyleGAN-V specific configuration for 1024x1024
stylegan:
  resolution: 1024
  architecture: "stylegan-v"
  z_dim: 512
  w_dim: 512
  mapping_layers: 8
  synthesis_layers: auto  # Auto-calculate for 1024x1024

# Sampling configuration
sampling:
  truncation_psi: 1.0
  num_samples: 16  # Samples per preview
  grid_size: [4, 4]  # 4x4 grid for previews

# Visualization configuration
visualizer:
  save_every_kimg: 100  # Save samples every 100k images
  output_dir: "samples"
  format: "png"
  quality: 95
  
# STRICT MODE SETTINGS
strict_mode:
  enabled: true
  enforce_dataset: "lukua/monox-dataset"
  require_authentication: true
  no_fallbacks: true
  validation_on_start: true

# Training launcher mode
launcher: stylegan  # Use StyleGAN-V launcher