# MonoX Visualizer Configuration
# ==============================
# Sample generation and monitoring for MonoX training
# ==============================

# Sample generation settings
sampling:
  num_samples: 16  # Generate 16 samples per visualization
  grid_size: [4, 4]  # 4x4 grid layout
  truncation_psi: 1.0  # Full diversity (no truncation)
  random_seed: null  # Random seed each time

# Output settings
output:
  format: "png"
  quality: 95
  dpi: 300
  save_individual: false  # Only save grid
  
# Visualization frequency
frequency:
  save_every_kimg: 100  # Save samples every 100k images
  preview_kimg: 50      # Quick previews every 50k images
  
# Directory structure
directories:
  output_dir: "samples"
  preview_dir: "previews"
  
# Sample types
sample_types:
  - type: "random"
    name: "random_samples"
    description: "Random samples from latent space"
    
  - type: "fixed_noise"
    name: "fixed_samples" 
    description: "Consistent samples for progress tracking"
    seed: 42
    
  - type: "interpolation"
    name: "interpolation"
    description: "Latent space interpolation"
    steps: 8

# Image processing
processing:
  resize_for_web: true
  web_resolution: 512  # Smaller version for web display
  maintain_aspect_ratio: true
  
# Monitoring integration
monitoring:
  tensorboard: true
  wandb: false  # Disabled for HF Spaces
  
# HF Model repository sync
sync:
  enabled: true
  repository: "lukua/monox-model"
  directory: "samples"
  commit_message: "Update training samples - epoch {epoch}"